Libreria/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Libreria import settings
from django.conf.urls.static import static
from Libreria.views import *


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^hola/$', hola),
    url(r'^fecha/$', fecha_actual),
    url(r'^fecha/mas/(\d{1,2})/$', horas_adelante),
    url(r'^atributos/$', atributos_meta),
    url(r'^biblioteca/', include('biblioteca.urls')),
    url(r'^contactos/', include('contactos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactos/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [

    url(r'^$', contactos, name='contactos'),
    url(r'^gracias/$', gracias, name='gracias'),
]

contactos/models.py
from django.db import models

# Create your models here.

contactos/forms.py
from django import forms

class FormContactos(forms.Form):
    asunto = forms.CharField(max_length=100)
    mensaje = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField(required=False, label='Tu correo electronico')

    def clean_mensaje(self):
        mensaje = self.cleaned_data['mensaje']
        num_palabras = len(mensaje.split())
        if num_palabras < 4:
            raise forms.ValidationError("Se requiere minimo 4 palabras")

        return mensaje

contactos/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.mail import send_mail
from django.shortcuts import render

from .forms import *

def contactos(request):
    if request.method == 'POST':
        form = FormContactos(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            return HttpResponseRedirect('/contactos/gracias')
    else:
        form = FormContactos(initial={'asunto': "¡Adoro tu sitio!"})

    return render(request, 'form_contactos.html', {'form': form})

def gracias(request):
    return HttpResponse("<h1>Gracias por tu mensaje</h1>")

contactos/templates/form_contactos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contactanos</title>
    <style>
        ul.errorlist{
            margin: 0;
            padding: 0;
        }

        .errorlist li {
            background-color: red;
            color: white;
            display: block;
            font-size: 10px;
            margin: 0 0 3px;
            padding: 4px 5px;
        }
    </style>
</head>
<body>
    <h1>Contactanos</h1>

    {% if form.errors %}
        <p style="color: red;">Corrige los siguiente:
        </p>
    {% endif %}

    <form action="" method="post">
        {% csrf_token %}

        <div class="field">
            {{ form.asunto.errors }}
                <label for="id_asunto">Asunto:</label>
            {{ form.asunto }}
        </div>

        <div class="field">
            {{ form.email.errors }}
                <label for="id_email">E-mail:</label>
            {{ form.email }}
        </div>

        <div class="field">
            {{ form.mensaje.errors }}
                <label for="id_mensaje">Mensaje:</label>
            {{ form.mensaje }}
        </div>

        <input type="submit" value="Enviar">
    </form>
</body>
</html>